### ISSUE TITLE
SPI pin configuration for stmcubemx.

### ISSUE THREAD

**Issue by djdlgl** [Spirit532/ADS1220_STM32_HAL#1] opened 2022-05-03 16:07 UTC
Hello! I want to use your code for operating ADS1220 but it is not very clear for me as there is no SPI pin configuration.

Could you please recommend me some?

Thank you for reading!

**Comment by Spirit532** [comment] 2022-05-03 16:10
Just configure SPI normally, follow the ADS1220 datasheet for communication mode.
The example in this repo uses SPI1.

**Comment by djdlgl** [comment] 2022-05-03 16:52
Thank you for rapid reply!

As I know for ADS1220, 5 pins needed to be port (SCKL, MOSI, MISO, CS, and DRDY).

According to your code, it seems you used CS as hardware set not software, is it correct way that I understand?

**Comment by Spirit532** [comment] 2022-05-03 18:29
Yes.

**Comment by kishore-se** [comment] 2023-06-19 10:15
Hello! I want to use your code for operating ADS1220 but giving improper ouput value

**Comment by Spirit532** [comment] 2023-06-19 16:31
> Hello! I want to use your code for operating ADS1220 but giving proper ouput value

Not sure what you mean by this.

**Comment by kishore-se** [comment] 2023-06-20 05:43
I was trying to use this code but the output value is improper, It generating only random value. I given analog value of 5v and 3.3v gets value of 440832 and 450725 when i reset the stm32 getting different value for same analog value of 5v as 740256and 3.3v 788557. I have attached
[ads_ex_ch.zip](https://github.com/Spirit532/ADS1220_STM32_HAL/files/11796275/ads_ex_ch.zip)
 my program file
Help! to fix it

**Comment by Spirit532** [comment] 2023-06-20 05:50
> I was trying to use this code but the output value is improper, It generating only random value. I given analog value of 5v and 3.3v gets value of 440832 and 450725 when i reset the stm32 getting different value for same analog value of 5v as 740256and 3.3v 788557. I have attached [ads_ex_ch.zip](https://github.com/Spirit532/ADS1220_STM32_HAL/files/11796275/ads_ex_ch.zip) my program file Help! to fix it

You're constantly reinitializing the chip.
I don't know what your schematic is and how everything else is connected, but I would recommend learning programming basics and reading through the code to figure out what it's actually doing.
I'm going to close this issue, if you find that the library itself is not functioning as intended please open another issue and describe what you've done to troubleshoot.

**Closed as completed by Spirit532** 2023-06-20 05:50 UTC
